### ISSUE TITLE
Themes load but get "No such file or directory" error when existing vim

### ISSUE THREAD

**Issue by giangvo** [nightsense/nemo#1]
Hi,

I am new to vim and trying to use `nemo-dark` theme. I installed the theme using `vim-plug`, theme loads correctly but I always get "No such file or directory" error when existing vim. Below is my vim config.
```
...
call plug#begin('~/.vim/plugged')
Plug 'nightsense/nemo'
call plug#end()
...
colorscheme nemo-dark
```
Full error that I am getting
```
/bin/sh: /Users/giangvo/.nightshell/nemo-dark: No such file or directory
```
There is no `.nightshell` folder in my machine and I wonder why vim is trying to lookup for that folder.

Could you help to check if I missed anything?

Thanks,
Giang

**Comment by nightsense** [comment]
Hi @giangvo, thanks for letting me know. You didn't miss anything, the issue was with the theme file: it was trying to run the script `~/.nightshell/nemo-dark` without first checking whether that script exists. The theme file should be fixed now, just run `PlugUpdate` to get the updated version.

(FYI "nightshell" is a [separate repository](https://github.com/nightsense/nightshell) that helps my themes function in terminals / terminal vim.)

**Comment by giangvo** [comment]
The fix works. 👍 Awesome! Thanks a lot for your super quick support.
